logging:
  config: classpath:logback-dev.xml
spring:
  data:
    mongodb:
      username: developer
      password: developer
      host: 120.79.145.235
      port: 27017
      database: starrysea-test
starrysea:
  split:
    input: D:/chatHistory/raw
    output: D:/chatHistory/result